"""empty message

Revision ID: 9a681d9313bb
Revises: 2536a9949e99
Create Date: 2020-04-06 22:09:06.926051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a681d9313bb'
down_revision = '2536a9949e99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('is_verified', sa.Boolean(create_constraint=()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'is_verified')
    # ### end Alembic commands ###
