"""empty message

Revision ID: b1ddbbd5af1f
Revises: 9a681d9313bb
Create Date: 2020-04-06 22:11:25.742693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1ddbbd5af1f'
down_revision = '9a681d9313bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
